# https://prometheus.io/docs/alerting/latest/configuration/
global:
  slack_api_url: ''

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#co2-alert'
